# Copyright 2024 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env AposAddSources')

srcs = [
  'tsan_test.c',
]

tsan_srcs = [
  'instrumented.c'
]

subdirs = []

tsan_env = env.Clone()
tsan_env.Append(CFLAGS = Split('-fsanitize=thread'))

objects = [env.Object(src) for src in srcs]
objects.append([tsan_env.Object(src) for src in tsan_srcs])
Return('objects')
