// Copyright 2014 Andrew Oates.  All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef APOO_TEST_HAMLET_H
#define APOO_TEST_HAMLET_H

// Act 1, scene 1 of Hamlet.
const char kHamlet[] =
    "ACT I\n"
    "\n"
    "SCENE I. Elsinore. A platform before the castle.\n"
    "\n"
    "FRANCISCO at his post. Enter to him BERNARDO\n"
    "BERNARDO\n"
    "Who's there?\n"
    "FRANCISCO\n"
    "Nay, answer me: stand, and unfold yourself.\n"
    "BERNARDO\n"
    "Long live the king!\n"
    "FRANCISCO\n"
    "Bernardo?\n"
    "BERNARDO\n"
    "He.\n"
    "FRANCISCO\n"
    "You come most carefully upon your hour.\n"
    "BERNARDO\n"
    "'Tis now struck twelve; get thee to bed, Francisco.\n"
    "FRANCISCO\n"
    "For this relief much thanks: 'tis bitter cold,\n"
    "And I am sick at heart.\n"
    "BERNARDO\n"
    "Have you had quiet guard?\n"
    "FRANCISCO\n"
    "Not a mouse stirring.\n"
    "BERNARDO\n"
    "Well, good night.\n"
    "If you do meet Horatio and Marcellus,\n"
    "The rivals of my watch, bid them make haste.\n"
    "FRANCISCO\n"
    "I think I hear them. Stand, ho! Who's there?\n"
    "Enter HORATIO and MARCELLUS\n"
    "\n"
    "HORATIO\n"
    "Friends to this ground.\n"
    "MARCELLUS\n"
    "And liegemen to the Dane.\n"
    "FRANCISCO\n"
    "Give you good night.\n"
    "MARCELLUS\n"
    "O, farewell, honest soldier:\n"
    "Who hath relieved you?\n"
    "FRANCISCO\n"
    "Bernardo has my place.\n"
    "Give you good night.\n"
    "Exit\n"
    "\n"
    "MARCELLUS\n"
    "Holla! Bernardo!\n"
    "BERNARDO\n"
    "Say,\n"
    "What, is Horatio there?\n"
    "HORATIO\n"
    "A piece of him.\n"
    "BERNARDO\n"
    "Welcome, Horatio: welcome, good Marcellus.\n"
    "MARCELLUS\n"
    "What, has this thing appear'd again to-night?\n"
    "BERNARDO\n"
    "I have seen nothing.\n"
    "MARCELLUS\n"
    "Horatio says 'tis but our fantasy,\n"
    "And will not let belief take hold of him\n"
    "Touching this dreaded sight, twice seen of us:\n"
    "Therefore I have entreated him along\n"
    "With us to watch the minutes of this night;\n"
    "That if again this apparition come,\n"
    "He may approve our eyes and speak to it.\n"
    "HORATIO\n"
    "Tush, tush, 'twill not appear.\n"
    "BERNARDO\n"
    "Sit down awhile;\n"
    "And let us once again assail your ears,\n"
    "That are so fortified against our story\n"
    "What we have two nights seen.\n"
    "HORATIO\n"
    "Well, sit we down,\n"
    "And let us hear Bernardo speak of this.\n"
    "BERNARDO\n"
    "Last night of all,\n"
    "When yond same star that's westward from the pole\n"
    "Had made his course to illume that part of heaven\n"
    "Where now it burns, Marcellus and myself,\n"
    "The bell then beating one,--\n"
    "Enter Ghost\n"
    "\n"
    "MARCELLUS\n"
    "Peace, break thee off; look, where it comes again!\n"
    "BERNARDO\n"
    "In the same figure, like the king that's dead.\n"
    "MARCELLUS\n"
    "Thou art a scholar; speak to it, Horatio.\n"
    "BERNARDO\n"
    "Looks it not like the king? mark it, Horatio.\n"
    "HORATIO\n"
    "Most like: it harrows me with fear and wonder.\n"
    "BERNARDO\n"
    "It would be spoke to.\n"
    "MARCELLUS\n"
    "Question it, Horatio.\n"
    "HORATIO\n"
    "What art thou that usurp'st this time of night,\n"
    "Together with that fair and warlike form\n"
    "In which the majesty of buried Denmark\n"
    "Did sometimes march? by heaven I charge thee, speak!\n"
    "MARCELLUS\n"
    "It is offended.\n"
    "BERNARDO\n"
    "See, it stalks away!\n"
    "HORATIO\n"
    "Stay! speak, speak! I charge thee, speak!\n"
    "Exit Ghost\n"
    "\n"
    "MARCELLUS\n"
    "'Tis gone, and will not answer.\n"
    "BERNARDO\n"
    "How now, Horatio! you tremble and look pale:\n"
    "Is not this something more than fantasy?\n"
    "What think you on't?\n"
    "HORATIO\n"
    "Before my God, I might not this believe\n"
    "Without the sensible and true avouch\n"
    "Of mine own eyes.\n"
    "MARCELLUS\n"
    "Is it not like the king?\n"
    "HORATIO\n"
    "As thou art to thyself:\n"
    "Such was the very armour he had on\n"
    "When he the ambitious Norway combated;\n"
    "So frown'd he once, when, in an angry parle,\n"
    "He smote the sledded Polacks on the ice.\n"
    "'Tis strange.\n"
    "MARCELLUS\n"
    "Thus twice before, and jump at this dead hour,\n"
    "With martial stalk hath he gone by our watch.\n"
    "HORATIO\n"
    "In what particular thought to work I know not;\n"
    "But in the gross and scope of my opinion,\n"
    "This bodes some strange eruption to our state.\n"
    "MARCELLUS\n"
    "Good now, sit down, and tell me, he that knows,\n"
    "Why this same strict and most observant watch\n"
    "So nightly toils the subject of the land,\n"
    "And why such daily cast of brazen cannon,\n"
    "And foreign mart for implements of war;\n"
    "Why such impress of shipwrights, whose sore task\n"
    "Does not divide the Sunday from the week;\n"
    "What might be toward, that this sweaty haste\n"
    "Doth make the night joint-labourer with the day:\n"
    "Who is't that can inform me?\n"
    "HORATIO\n"
    "That can I;\n"
    "At least, the whisper goes so. Our last king,\n"
    "Whose image even but now appear'd to us,\n"
    "Was, as you know, by Fortinbras of Norway,\n"
    "Thereto prick'd on by a most emulate pride,\n"
    "Dared to the combat; in which our valiant Hamlet--\n"
    "For so this side of our known world esteem'd him--\n"
    "Did slay this Fortinbras; who by a seal'd compact,\n"
    "Well ratified by law and heraldry,\n"
    "Did forfeit, with his life, all those his lands\n"
    "Which he stood seized of, to the conqueror:\n"
    "Against the which, a moiety competent\n"
    "Was gaged by our king; which had return'd\n"
    "To the inheritance of Fortinbras,\n"
    "Had he been vanquisher; as, by the same covenant,\n"
    "And carriage of the article design'd,\n"
    "His fell to Hamlet. Now, sir, young Fortinbras,\n"
    "Of unimproved mettle hot and full,\n"
    "Hath in the skirts of Norway here and there\n"
    "Shark'd up a list of lawless resolutes,\n"
    "For food and diet, to some enterprise\n"
    "That hath a stomach in't; which is no other--\n"
    "As it doth well appear unto our state--\n"
    "But to recover of us, by strong hand\n"
    "And terms compulsatory, those foresaid lands\n"
    "So by his father lost: and this, I take it,\n"
    "Is the main motive of our preparations,\n"
    "The source of this our watch and the chief head\n"
    "Of this post-haste and romage in the land.\n"
    "BERNARDO\n"
    "I think it be no other but e'en so:\n"
    "Well may it sort that this portentous figure\n"
    "Comes armed through our watch; so like the king\n"
    "That was and is the question of these wars.\n"
    "HORATIO\n"
    "A mote it is to trouble the mind's eye.\n"
    "In the most high and palmy state of Rome,\n"
    "A little ere the mightiest Julius fell,\n"
    "The graves stood tenantless and the sheeted dead\n"
    "Did squeak and gibber in the Roman streets:\n"
    "As stars with trains of fire and dews of blood,\n"
    "Disasters in the sun; and the moist star\n"
    "Upon whose influence Neptune's empire stands\n"
    "Was sick almost to doomsday with eclipse:\n"
    "And even the like precurse of fierce events,\n"
    "As harbingers preceding still the fates\n"
    "And prologue to the omen coming on,\n"
    "Have heaven and earth together demonstrated\n"
    "Unto our climatures and countrymen.--\n"
    "But soft, behold! lo, where it comes again!\n"
    "Re-enter Ghost\n"
    "\n"
    "I'll cross it, though it blast me. Stay, illusion!\n"
    "If thou hast any sound, or use of voice,\n"
    "Speak to me:\n"
    "If there be any good thing to be done,\n"
    "That may to thee do ease and grace to me,\n"
    "Speak to me:\n"
    "Cock crows\n"
    "\n"
    "If thou art privy to thy country's fate,\n"
    "Which, happily, foreknowing may avoid, O, speak!\n"
    "Or if thou hast uphoarded in thy life\n"
    "Extorted treasure in the womb of earth,\n"
    "For which, they say, you spirits oft walk in death,\n"
    "Speak of it: stay, and speak! Stop it, Marcellus.\n"
    "MARCELLUS\n"
    "Shall I strike at it with my partisan?\n"
    "HORATIO\n"
    "Do, if it will not stand.\n"
    "BERNARDO\n"
    "'Tis here!\n"
    "HORATIO\n"
    "'Tis here!\n"
    "MARCELLUS\n"
    "'Tis gone!\n"
    "Exit Ghost\n"
    "\n"
    "We do it wrong, being so majestical,\n"
    "To offer it the show of violence;\n"
    "For it is, as the air, invulnerable,\n"
    "And our vain blows malicious mockery.\n"
    "BERNARDO\n"
    "It was about to speak, when the cock crew.\n"
    "HORATIO\n"
    "And then it started like a guilty thing\n"
    "Upon a fearful summons. I have heard,\n"
    "The cock, that is the trumpet to the morn,\n"
    "Doth with his lofty and shrill-sounding throat\n"
    "Awake the god of day; and, at his warning,\n"
    "Whether in sea or fire, in earth or air,\n"
    "The extravagant and erring spirit hies\n"
    "To his confine: and of the truth herein\n"
    "This present object made probation.\n"
    "MARCELLUS\n"
    "It faded on the crowing of the cock.\n"
    "Some say that ever 'gainst that season comes\n"
    "Wherein our Saviour's birth is celebrated,\n"
    "The bird of dawning singeth all night long:\n"
    "And then, they say, no spirit dares stir abroad;\n"
    "The nights are wholesome; then no planets strike,\n"
    "No fairy takes, nor witch hath power to charm,\n"
    "So hallow'd and so gracious is the time.\n"
    "HORATIO\n"
    "So have I heard and do in part believe it.\n"
    "But, look, the morn, in russet mantle clad,\n"
    "Walks o'er the dew of yon high eastward hill:\n"
    "Break we our watch up; and by my advice,\n"
    "Let us impart what we have seen to-night\n"
    "Unto young Hamlet; for, upon my life,\n"
    "This spirit, dumb to us, will speak to him.\n"
    "Do you consent we shall acquaint him with it,\n"
    "As needful in our loves, fitting our duty?\n"
    "MARCELLUS\n"
    "Let's do't, I pray; and I this morning know\n"
    "Where we shall find him most conveniently.\n"
    "Exeunt\n";

#endif
