#!/usr/bin/env python3
# Copyright 2026 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Builds all artifacts based on the currently-configured build system.

import os
import subprocess
import sys

def run_cmd(cmd, stdout):
  print('Running: ' + subprocess.list2cmdline(cmd))
  proc = subprocess.run(cmd, stdout=stdout)
  if proc.returncode != 0:
    sys.exit(proc.returncode)

link = os.readlink('out')
if link == 'build-scons':
  cmd = ['scons', '--implicit-cache', '--max-drift=1']
elif link == 'out-gn':
  cmd = ['ninja', '-C', 'out/latest']
else:
  print(f'Unknown build system, "out" is linked to "{link}"', file=sys.stderr)
  sys.exit(1)

run_cmd(cmd, stdout=sys.stdout)

if link == 'out-gn':
  with open('out/latest/compile_commands.json', 'w') as f:
    run_cmd(cmd + ['-t', 'compdb'], stdout=f)
