# Copyright 2015 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env AposAddSources')

srcs = [
  'interrupt_test.c',
  'page_alloc_map_test.c',
]

subdirs = []

# TODO(aoates): figure out how to merge this with test/SConscript section.
extra_cflags = ['-Wframe-larger-than=5000']
if env['CLANG']:
  extra_cflags.append('-Wno-self-assign')

objects = AposAddSources(env, srcs, subdirs,
    CFLAGS=env['CFLAGS'] + extra_cflags)
Return('objects')
