// Copyright 2025 Andrew Oates.  All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Special symbols generated by the linker scripts to guide layout of the kernel
// binary in memory.  Should only be used in arch-specific loading code and, if
// necessary, very specific fast-paths.
#ifndef APOO_COMMON_LINKER_SYMBOLS_H
#define APOO_COMMON_LINKER_SYMBOLS_H

// Symbols that mark the start and end of the kernel image's virtual memory
// addresses overall.
extern int KERNEL_START_SYMBOL, KERNEL_END_SYMBOL;

// Symbols that mark the start and end of the writable portion of the kernel
// image's virtual memory region (.data/.bss sections).
extern int KERNEL_DATA_START, KERNEL_DATA_END;

#endif
