# Copyright 2014 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env')

srcs = ['builtins.c', 'errno.c',
    'hash.c',
    'hashtable.c',
    'kassert.c',
    'klog.c',
    'kprintf.c',
    'kstring.c',
    'list.c']

def config_h_builder(target, source, env):
  """Builder for a config.h header file."""
  for a_target, a_source in zip(target, source):
      config_h = file(str(a_target), "w")
      config_h_in = file(str(a_source), "r")
      config_h.write(config_h_in.read() % env.Dictionary())
      config_h_in.close()
      config_h.close()

env.AlwaysBuild(env.Command('config.h', 'config.h.in', config_h_builder))

objects = [env.Object(src) for src in srcs]
Return('objects')
