# Copyright 2024 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env AposAddSources')

srcs = [
  'tsan.c',
  'tsan_access.c',
  'tsan_atomic_hooks.c',
  'tsan_event.c',
  'tsan_hooks.c',
  'tsan_sync.c',
  'tsan_thread.c',
  'vector_clock.c',
]

subdirs = []

tsan_env = env.Clone()
# TODO(tsan): increase this to -O2 or -O3
tsan_env.Append(CFLAGS = Split('-O1'))
tsan_env.Append(CFLAGS = Split('-fno-omit-frame-pointer'))

# TODO(aoates): reduce function stack size to eliminate this change.
env.Append(CFLAGS = Split('-Wframe-larger-than=2500'))

if env['TSAN_FULL']:
  env.Append(CFLAGS = Split('-fsanitize=thread'))
  env.Append(CFLAGS = Split('-O1 -fno-omit-frame-pointer'))

objects = [tsan_env.Object(src) for src in srcs]
Return('objects')
