# Copyright 2023 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env AposAddSources')

DTS_FILES = [
  'large_golden.dts',
  'small_golden.dts',
]

def dts_to_header(target, source, env):
  return env.Execute(('dtc -I dts -O dtb %s ' +
                      '| xxd -i ' +
                      '| cat build/license_template.h - > %s') %
                     (source[0], target[0].path))

for src in DTS_FILES:
  env.Command('#test/dtb_testdata/${SOURCE}.h', src, dts_to_header)

Return([])
