# Copyright 2014 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env user_env')

# A dummy library that builds the user syscall stubs against system headers to
# make sure they can be compiled.
if user_env['USER_DUMMY_LIB']:
  user_env.StaticLibrary('apos_user_dummy', [
      'syscall.s',
      'newlib_syscall_stubs.tpl.c',
      ])

env.Tpl('syscall_stubs.tpl')
env.Tpl('newlib_syscall_stubs.tpl')
env.Tpl('newlib_syscall_stubs_manual.tpl')

SConscript('include/SConscript')
