# Copyright 2014 Andrew Oates.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env AposAddSources')

srcs = [
    'arch/dev/interrupts.c',
    'arch/dev/irq.c',
    'arch/dev/isr.s',
    'arch/memory/page_alloc.c',
    'arch/memory/page_fault.c',
    'arch/proc/kthread.c',
    'arch/proc/kthread_asm.s',
    'arch/proc/signal/signal_enter.c',
    'arch/proc/signal/sigreturn_trampoline.s',
    'arch/proc/stack_trace.c',
    'arch/proc/user_context.c',
    'arch/proc/user_context_asm.s',
    'arch/proc/user_mode.c',
    'arch/syscall/context.c',
    'arch/syscall/init.c',
    'arch/syscall/syscall_enter.s',
    'internal/dev/faults.c',
    'internal/memory/gdt.c',
    'internal/proc/tss.c',
    ]

subdirs = ['internal/load', '../x86-common']

env.Prepend(CPPPATH = ['#/archs/x86-common'])

objects = AposAddSources(env, srcs, subdirs)
objects.append(env.PhysObject('internal/memory/gdt.c'))
Return('objects')
